In [2]:
import numpy as np
import pandas as pd

In [20]:
df = pd.DataFrame(data={'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]}, 
                  index=['a', 'b', 'c'])

# Convert the entire DataFrame
df.to_numpy()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int64)

In [21]:
#Write to csv
df.to_excel("D:/temp/output.xls")

In [54]:
rdf = pd.read_excel("C:/temp/M.xls",index_col=0)
rdf

FileNotFoundError: [Errno 2] No such file or directory: 'C:/temp/M.xls'

In [31]:
df.to_csv('C:/Users/CluClu/Downloads/Maggioni Python/SOD_Utils/trajdata.csv')

(19, 199)

In [32]:
A

array([[-1.28392835, -1.50813926, -1.65433886, ..., -1.29483938,
        -1.36900981, -1.46475064],
       [ 0.83870575,  0.98892924,  1.01659094, ..., -2.14375005,
        -2.31030051, -2.47999614],
       [-1.25216001, -1.43060464, -1.47390977, ...,  0.62832188,
         0.49951005,  0.35845892],
       ...,
       [ 0.61659492,  0.55583925,  0.50679581, ...,  1.79903214,
         1.73205019,  1.64319946],
       [-0.08378415, -0.21128152, -0.31609982, ..., -0.51060703,
        -0.66419535, -0.82511147],
       [-0.65926079, -0.86257759, -0.93593937, ...,  0.43690194,
         0.35547935,  0.25311792]])

In [33]:
np.round(A,4)

array([[-1.2839, -1.5081, -1.6543, ..., -1.2948, -1.369 , -1.4648],
       [ 0.8387,  0.9889,  1.0166, ..., -2.1438, -2.3103, -2.48  ],
       [-1.2522, -1.4306, -1.4739, ...,  0.6283,  0.4995,  0.3585],
       ...,
       [ 0.6166,  0.5558,  0.5068, ...,  1.799 ,  1.7321,  1.6432],
       [-0.0838, -0.2113, -0.3161, ..., -0.5106, -0.6642, -0.8251],
       [-0.6593, -0.8626, -0.9359, ...,  0.4369,  0.3555,  0.2531]])

In [35]:
import numpy as np
 
np.set_printoptions(suppress=True, formatter={'float_kind':'{:0.6f}'.format})
 
a = np.array([1.8e-10, 1.586, 150.45, 0.2855])  
 
print(a)

[0.000000 1.586000 150.450000 0.285500]


In [36]:
import numpy as np
foo_array = [38,26,14,55,31,0,15,8,0,0,0,18,40,27,3,19,0,49,29,21,5,38,29,17,16]
foo = np.array(foo_array)
# Compute the median of the non-zero elements
m = np.median(foo[foo > 0])
# Assign the median to the zero elements 
foo[foo == 0] = m
foo

array([38, 26, 14, 55, 31, 23, 15,  8, 23, 23, 23, 18, 40, 27,  3, 19, 23,
       49, 29, 21,  5, 38, 29, 17, 16])

In [86]:
from scipy.integrate import ode

y0, t0 = [1.0j, 2.0], 0

def f(t, y, arg1):
    return [1j*arg1*y[0] + y[1], -arg1*y[1]**2]

def jac(t, y, arg1):
    return [[1j*arg1, 1], [0, -arg1*2*y[1]]]



In [88]:
r = ode(f).set_integrator('zvode', method='bdf')
r.set_initial_value(y0, t0).set_f_params(3.0)
t1 = 10
dt = 1
while r.successful() and r.t < t1:
    r.integrate(r.t+dt)
    print((r.t, r.y))

(1.0, array([-0.3432716 -0.58873233j,  0.28571612+0.j        ]))
(2.0, array([0.40748964+0.67139406j, 0.15384677+0.j        ]))
(3.0, array([-0.50168074-0.52296894j,  0.10526345+0.j        ]))
(4.0, array([0.56979439+0.50782088j, 0.08000017+0.j        ]))
(5.0, array([-0.63542344-0.37461758j,  0.06451624+0.j        ]))
(6.0, array([0.68263266+0.32042453j, 0.05405413+0.j        ]))
(7.0, array([-0.7201423 -0.18757413j,  0.04651169+0.j        ]))
(8.0, array([0.74032053+0.1130171j, 0.04081637+0.j       ]))
(9.0, array([-0.74791996+0.01817806j,  0.03636367+0.j        ]))
(10.0, array([0.7387785 -0.1006028j, 0.03278691+0.j       ]))


In [57]:
def odefun(t, y, sys_info):
    MAURO = False
    #The following code will replace zero with median value
    #med = np.median(r[r > 0]) 
    #r[r == 0] = med

    if not MAURO:
        f = 1 - sys_info**(-2)
    else:
        f = 1 - sys_info**(-6)
   
    return f


# state_vars = partition_sys_var(y, sys_info)
#def eval_rhs(y, sys_info):
#   state_vars = partition_sys_var(y, sys_info)
#    return state_vars
#pdist_mat = np.sqrt(np.abs(sqdist_mod(x))) 
prey_attract_prey = 1
arg_1 = [0.188236228393228,0.313727047322047,0.439217866250866,0.564708685179685,0.690199504108504,0.815690323037322,0.941181141966141,
1.06667196089496,1.19216277982378,1.3176535987526,1.44314441768142,1.56863523661024,1.69412605553905,1.81961687446787,
1.94510769339669,2.07059851232551,2.19608933125433,2.32158015018315,2.44707096911197,2.57256178804079,2.6980526069696,
2.82354342589842,2.94903424482724,3.07452506375606,3.200015883]
y0 =[ -0.00872886532924586,
-0.0484557968079573,-0.0171359272631671,0.0136419363689843,-0.0754701451475953,-0.0364264003889999,-0.0314578552365636,
-0.0759592943174865,0.0358626619163718,0.079062482662237,-0.00464637532356709,-0.0573029485604983,-0.044418547425838,
-0.0252458827507441,0.0643476495508173,0.067326157152198,0.0218279649314381,-0.024553876138852,0.0360676981992193,
-0.0305536793525595]
t0 =np.linspace(0,5,5)

In [ ]:
#self_organized_dynamics
#def self_organized_dynamics(y_init, sys_info, solver_info):
#for m in range(M):
#        if comp_traj:
#            traj[m] = self_organized_dynamics(ICs[:, m], sys_info, solver_info)
#dynamics = ode(odefun).set_integrator('zvode', method='bdf', with_jacobian=True)
#dynamics.set_initial_value(y_init, solver_info['time_span']).set_odefun_params(sys_info,)
#return dynamics

In [ ]:
block_size = sys_info.d * sys_info.N;
x          = reshape(y(1 : block_size), [sys_info.d, sys_info.N]);

In [46]:
t0 =np.linspace(0,5,5)

In [47]:
t0

array([0.000000, 1.250000, 2.500000, 3.750000, 5.000000])

In [188]:
def f(t, u,arg1):
    f = 1 - arg1**(-2)
    return f

from scipy.integrate import ode
r = ode(f).set_integrator('zvode', method='bdf')
arg_1 =6.18823622                           
u0 = [0.0218279649314381]
r.set_initial_value(u0, 0).set_f_params(arg_1)
T = 30
dt = T/20.
u = [];  t = []
while r.successful() and r.t <= T:
    r.integrate(r.t + dt)
    u.append(r.y);  t.append(r.t)
print(r.get_return_code())

2


In [107]:
A=np.array(u)
A.shape

(21, 1)

In [108]:
np.set_printoptions(suppress=True, formatter={'float_kind':'{:0.6f}'.format})
print(A)


[[ 1.48265761+0.j]
 [ 2.94348726+0.j]
 [ 4.4043169 +0.j]
 [ 5.86514655+0.j]
 [ 7.3259762 +0.j]
 [ 8.78680584+0.j]
 [10.24763549+0.j]
 [11.70846514+0.j]
 [13.16929478+0.j]
 [14.63012443+0.j]
 [16.09095408+0.j]
 [17.55178372+0.j]
 [19.01261337+0.j]
 [20.47344301+0.j]
 [21.93427266+0.j]
 [23.39510231+0.j]
 [24.85593195+0.j]
 [26.3167616 +0.j]
 [27.77759125+0.j]
 [29.23842089+0.j]
 [30.69925054+0.j]]


In [120]:
y0 =[ -0.00872886532924586,
-0.0484557968079573,-0.0171359272631671,0.0136419363689843,-0.0754701451475953,-0.0364264003889999,-0.0314578552365636,
-0.0759592943174865,0.0358626619163718,0.079062482662237,-0.00464637532356709,-0.0573029485604983,-0.044418547425838,
-0.0252458827507441,0.0643476495508173,0.067326157152198,0.0218279649314381,-0.024553876138852,0.0360676981992193,
-0.0305536793525595]
y0 = np.array(y0)
p=y0.reshape(2,10)
p

array([[-0.008729, -0.048456, -0.017136, 0.013642, -0.075470, -0.036426,
        -0.031458, -0.075959, 0.035863, 0.079062],
       [-0.004646, -0.057303, -0.044419, -0.025246, 0.064348, 0.067326,
        0.021828, -0.024554, 0.036068, -0.030554]])

In [136]:
p=np.array([[1.069269, -0.653360, 0.818944, -0.441508, 0.980443, -0.539782,
        -0.808354, -0.790201, -1.153940, -0.092641],
       [0.271716, 1.139082, -0.422112, -1.116412, -0.765612, 0.875512,
        0.584265, 0.292626, -0.368277, 0.032675]])
p.shape

(2, 10)

In [165]:
y_init = np.array([-1.05825811,  0.12962493, -0.40147314,  0.2344644 , -0.87444586,
        0.16297107,  1.10424671, -0.80213584,  0.97391083,  0.0589306 ,
        0.49475021, -1.00922335, -0.61129238,  0.71026633, -0.21276029,
       -0.99128189,  0.14692584,  0.26459816, -0.05286884, -0.06734426])
y_init = y_init.reshape(2,10)
p = y_init

In [166]:
import numpy.matlib as mtlb
d, pn = p.shape
p=np.reshape(p,(d,pn))
#print("Shape for p and q)")
#print(p.shape)
qn = pn


pmag = np.sum(p * p, axis = 0)
pmag=np.reshape(pmag,(1,pn))
qmag = pmag
m = np.abs(mtlb.repmat(qmag, pn, 1) + mtlb.repmat(pmag.T, 1, qn) - 2 * np.dot(p.T,p))
np.fill_diagonal(m, 0)
m

array([[0.000000, 3.673003, 1.654697, 1.717579, 0.534358, 3.699692,
        4.797409, 0.118569, 4.429597, 1.564061],
       [3.673003, 0.000000, 0.440414, 2.967636, 1.642512, 0.001434,
        2.286569, 2.490799, 1.627433, 0.892134],
       [1.654697, 0.440414, 0.000000, 2.150934, 0.382531, 0.462989,
        2.842087, 0.927715, 2.203518, 0.507851],
       [1.717579, 2.967636, 2.150934, 0.000000, 2.081660, 2.900378,
        1.073874, 1.273160, 1.129156, 0.635490],
       [0.534358, 1.642512, 0.382531, 2.081660, 0.000000, 1.682330,
        4.044598, 0.233100, 3.441988, 0.892337],
       [3.699692, 0.001434, 0.462989, 2.900378, 1.682330, 0.000000,
        2.181517, 2.508666, 1.538242, 0.864485],
       [4.797409, 2.286569, 2.842087, 1.073874, 4.044598, 2.181517,
        0.000000, 3.648141, 0.056905, 1.138597],
       [0.118569, 2.490799, 0.927715, 1.273160, 0.233100, 2.508666,
        3.648141, 0.000000, 3.255127, 0.851621],
       [4.429597, 1.627433, 2.203518, 1.129156, 3.441988, 1.5382

In [167]:
m.shape

(10, 10)

In [130]:
m[1,:]

array([0.004351, 0.000000, 0.001147, 0.004884, 0.015529, 0.015677,
       0.006551, 0.001829, 0.015828, 0.016976])

In [124]:
np.dot(p.T,p)

array([[0.000098, 0.000689, 0.000356, -0.000002, 0.000360, 0.000005,
        0.000173, 0.000777, -0.000481, -0.000548],
       [0.000689, 0.005632, 0.003376, 0.000786, -0.000030, -0.002093,
        0.000274, 0.005088, -0.003805, -0.002080],
       [0.000356, 0.003376, 0.002267, 0.000888, -0.001565, -0.002366,
        -0.000431, 0.002392, -0.002217, 0.000002],
       [-0.000002, 0.000786, 0.000888, 0.000823, -0.002654, -0.002197,
        -0.000980, -0.000416, -0.000421, 0.001850],
       [0.000360, -0.000030, -0.001565, -0.002654, 0.009836, 0.007081,
        0.003779, 0.004153, -0.000386, -0.007933],
       [0.000005, -0.002093, -0.002366, -0.002197, 0.007081, 0.005860,
        0.002615, 0.001114, 0.001122, -0.004937],
       [0.000173, 0.000274, -0.000431, -0.000980, 0.003779, 0.002615,
        0.001466, 0.001854, -0.000341, -0.003154],
       [0.000777, 0.005088, 0.002392, -0.000416, 0.004153, 0.001114,
        0.001854, 0.006373, -0.003610, -0.005255],
       [-0.000481, -0.003805, -

In [125]:
p * p

array([[0.000076, 0.002348, 0.000294, 0.000186, 0.005696, 0.001327,
        0.000990, 0.005770, 0.001286, 0.006251],
       [0.000022, 0.003284, 0.001973, 0.000637, 0.004141, 0.004533,
        0.000476, 0.000603, 0.001301, 0.000934]])

In [153]:
type_info=np.array([1,1,1,1,1,1,2])
preys_ind = np.where(type_info ==1,1,0)
num_preys = np. count_nonzero(np.array(preys_ind))
print(num_preys)

6


In [154]:
l1 = [0.05, 0.15] 
domain = [i* num_preys for i in l1]
domain

[0.30000000000000004, 0.8999999999999999]

In [156]:
preds_ind = np.where(type_info ==2,1,0)
num_preds = np.count_nonzero(preds_ind)
preds_ind

array([0, 0, 0, 0, 0, 0, 1])

In [157]:
w = np.array([[-0.7717593, -1.0969517, 0.4904334, -1.1987274, 1.0881670,
        1.0375166, -0.5935011, -1.1676089, -1.0381189],
       [-0.4163131, -0.0208999, 0.2306007, -0.4954527, 0.1749723,
        -0.2291350, -0.6705024, -0.0509902, 0.1113019]])
w.shape

(2, 9)

In [158]:
y_init = np.zeros((2, 10))

In [160]:
y_init[:,0:9] = w

In [161]:
y_init

array([[-0.771759, -1.096952, 0.490433, -1.198727, 1.088167, 1.037517,
        -0.593501, -1.167609, -1.038119, 0.000000],
       [-0.416313, -0.020900, 0.230601, -0.495453, 0.174972, -0.229135,
        -0.670502, -0.050990, 0.111302, 0.000000]])

In [185]:
from scipy.integrate import ode                           
                                                  
 
# Function defining derivates of the positions and velocities.                                                            
def sho(t,y,k,m):                                            
    # INPUTS:                                                
        # t time, only used in non-autonomous systems.       
        # y[0] the x-position                                
        # y[1] the velocity                                  
        # k Spring constant                                  
        # m Mass                                             
    # OUTPUTS:
        # dxdt derivative of the position = velocity
        # dvdy acceleration, Newton's second law, here for a spring a = -k/m x
    return np.array([y[1], -k/m*y[0]])
 
# Initial Conditions
y0, t0 = [1.,0.], 0.
 
# Model parameters 
k = 1.      # Spring constant
m = 1.      # Mass on the Spring
 
# CREATE ODE OBJECT
i = ode(sho) # Create an ode object and bind the rhs function.
i.set_integrator('vode',method='adams')  # Which integrator to use. 
i.set_initial_value(y0,t0)  # The initial values
# Define parameters for the derivatives function. 
# These will be passed  to the function at each time.
i.set_f_params(k,m)         
 
tf = 5.       # Final time
dt = 0.25                  # Output interval
yf=[y0]                    # List for storing the output
times = np.arange(t0,tf,dt)    # Times to evaluate a solution. 
 
# Main loop for the integration
for t in times[1:]:
    i.integrate(i.t+dt)
    yf.append(i.y)
 
yf = np.array(yf)


In [184]:
yf

array([[1.000000, 0.000000],
       [0.968913, -0.247404],
       [0.877584, -0.479426],
       [0.731690, -0.681640],
       [0.540303, -0.841472],
       [0.315322, -0.948986],
       [0.070737, -0.997496],
       [-0.178247, -0.983987],
       [-0.416148, -0.909298],
       [-0.628175, -0.778073],
       [-0.801145, -0.598471],
       [-0.924304, -0.381660],
       [-0.989994, -0.141118],
       [-0.994130, 0.108198],
       [-0.936456, 0.350786],
       [-0.820558, 0.571564],
       [-0.653642, 0.756805],
       [-0.446085, 0.894991],
       [-0.210793, 0.977531],
       [0.037606, 0.999293]])

In [55]:
plot_info = {'sys_info': 'sys_info',
    'solver_info': 'solver_info',
    'obs_info': 'obs_info',
    'learn_info': 'learn_info'
}

In [35]:
, columns=['sys_info',  'solver_info','obs_info' 'learn_info' orient='index', columns=[K,V]]

("columns=['sys_info',",
 "'solver_info','obs_info'",
 "'learn_info'",
 "orient='index',",
 'columns=[K,V]]')

In [44]:
df = pd.DataFrame.from_dict(plot_info, orient='index')

In [37]:
df

0
sys_info        sys_info
solver_info  solver_info
obs_info        obs_info
learn_info    learn_info

In [47]:
A=df.to_dict()

In [49]:
A

{0: {'sys_info': 'sys_info',
  'solver_info': 'solver_info',
  'obs_info': 'obs_info',
  'learn_info': 'learn_info'}}

In [52]:
A[0]['sys_info']

'sys_info'

In [57]:
with open('C:/Users/CluClu/Downloads/Maggioni Python/SOD_Utils/test_data.txt','w') as data: 
      data.write(str(plot_info))

In [72]:
st1 = 'lamda  : f(r,k=1)'

In [73]:
a = st1.split(':')[0]
b =a.split(" ")[1]
if len(b) == 0:
    print('Empty')
else:
    print('There is a paarmeter')

Empty


In [74]:

type(b)

str

In [75]:
if len(b) == 0:
    print('Empty')
else:
    print('There is a paarmeter')

Empty


In [79]:
import numpy as np

In [80]:
a = np.array([ 1.11603504e+00, -1.19771911e-01,  3.93543426e-01, -1.97099070e-01,
        1.77187177e-01,  6.31133829e-01,  1.13920202e+00,  4.76617742e-01,
       -7.58153276e-02, -1.06772730e+00, -6.50627960e-04,  1.17741924e+00,
       -7.95691006e-01, -1.29385464e+00,  8.89603128e-01,  6.95605715e-01,
        5.37374128e-01,  1.09738661e-01, -5.77865405e-02])

In [81]:
a[1:]

array([-1.19771911e-01,  3.93543426e-01, -1.97099070e-01,  1.77187177e-01,
        6.31133829e-01,  1.13920202e+00,  4.76617742e-01, -7.58153276e-02,
       -1.06772730e+00, -6.50627960e-04,  1.17741924e+00, -7.95691006e-01,
       -1.29385464e+00,  8.89603128e-01,  6.95605715e-01,  5.37374128e-01,
        1.09738661e-01, -5.77865405e-02])

In [82]:
a[:1]

array([1.11603504])

In [83]:
a[6:]

array([ 1.13920202e+00,  4.76617742e-01, -7.58153276e-02, -1.06772730e+00,
       -6.50627960e-04,  1.17741924e+00, -7.95691006e-01, -1.29385464e+00,
        8.89603128e-01,  6.95605715e-01,  5.37374128e-01,  1.09738661e-01,
       -5.77865405e-02])

In [85]:
A=np.zeros(((4,5)))

In [88]:
A

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [93]:
A[3:]

array([[0., 0., 0., 0., 0.]])